server {
  listen       4200;
  server_name  localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    # if you want nginx to proxy API to backend (optional)
    # proxy_pass http://backend:8080/api/;
  }

  # optional gzip
  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
}
